function swings(c,n=3){const hi=[],lo=[];for(let i=n;i<c.length-n;i++){let H=1,L=1;for(let j=1;j<=n;j++){if(c[i].h<=c[i-j].h||c[i].h<=c[i+j].h)H=0;if(c[i].l>=c[i-j].l||c[i].l>=c[i+j].l)L=0}if(H)hi.push(i);if(L)lo.push(i)}return{hi,lo}}
function ema(c,p){const k=2/(p+1);let v=c[0].c;for(const x of c)v=x.c*k+v*(1-k);return v}
function atr(c,p=14){const a=[];for(let i=1;i<c.length;i++)a.push(Math.max(c[i].h-c[i].l,Math.abs(c[i].h-c[i-1].c),Math.abs(c[i].l-c[i-1].c)));return a.length<p?0:a.slice(-p).reduce((x,y)=>x+y,0)/p}
function session(t){const h=new Date(t).getUTCHours();return h>=7&&h<=14}
function trend(c){if(c.length<60)return'NEUTRAL';const x=c.slice(-60),e20=ema(x.slice(-30),20),e50=ema(x,50),p=x.at(-1).c;return e20>e50&&p>e20?'BULLISH':e20<e50&&p<e20?'BEARISH':'NEUTRAL'}
function body(x){return Math.abs(x.c-x.o)/(x.h-x.l||1)}
export function evaluateCoreA({m5,h1,d1,now=Date.now()}){const c=m5.filter(x=>x.t+300000<=now);if(c.length<120)return{signal:'WAIT',reason:'WAITING FOR MARKET DATA'};const price=c.at(-1).c,last=c.length-1,A=atr(c),db=trend(d1.filter(x=>x.t+86400000<=now)),hb=trend(h1.filter(x=>x.t+3600000<=now)),b=db===hb?db:'NEUTRAL';if(!session(c[last].t))return{signal:'WAIT',reason:'OFF SESSION — LONDON/NY OPEN ONLY',bias:b,price,rr:2};if(b==='NEUTRAL')return{signal:'WAIT',reason:'HTF TREND NOT ALIGNED',bias:b,price,rr:2};const {hi,lo}=swings(c,3);
for(let s=last-4;s>=Math.max(25,last-36);s--){const ph=hi.filter(i=>i<s).at(-1),pl=lo.filter(i=>i<s).at(-1);if(ph==null||pl==null)continue;const x=c[s],range=x.h-x.l;
if(b==='BULLISH'&&x.l<c[pl].l&&x.c>c[pl].l&&body(x)>=.45&&x.c>x.l+range*.55&&c[pl].l-x.l>=A*.25){let m=-1;for(let i=s+1;i<Math.min(last,s+9);i++)if(c[i].c>c[ph].h&&body(c[i])>=.65&&c[i].c-c[ph].h>=A*.35){m=i;break}if(m<0)continue;const low=Math.min(...c.slice(s,m+1).map(z=>z.l)),entry=low+(c[m].h-low)*.5,sl=low-A*.1,risk=entry-sl;if(risk<A*.45||risk>A*1.8)continue;if(last-m>18)continue;if(c.slice(m+1,last+1).some(z=>z.l<=entry&&z.h>=entry))return{signal:'BUY',reason:'DAILY + H1 BULLISH • STRONG SWEEP • DISPLACEMENT MSS • RETRACEMENT',bias:b,price,entry,sl,tp1:entry+risk*2,tp2:entry+risk*3,rr:2,risk,confidence:'VERY HIGH',session:'LONDON/NY OPEN'}}
if(b==='BEARISH'&&x.h>c[ph].h&&x.c<c[ph].h&&body(x)>=.45&&x.c<x.h-range*.55&&x.h-c[ph].h>=A*.25){let m=-1;for(let i=s+1;i<Math.min(last,s+9);i++)if(c[i].c<c[pl].l&&body(c[i])>=.65&&c[pl].l-c[i].c>=A*.35){m=i;break}if(m<0)continue;const top=Math.max(...c.slice(s,m+1).map(z=>z.h)),entry=top-(top-c[m].l)*.5,sl=top+A*.1,risk=sl-entry;if(risk<A*.45||risk>A*1.8)continue;if(last-m>18)continue;if(c.slice(m+1,last+1).some(z=>z.l<=entry&&z.h>=entry))return{signal:'SELL',reason:'DAILY + H1 BEARISH • STRONG SWEEP • DISPLACEMENT MSS • RETRACEMENT',bias:b,price,entry,sl,tp1:entry-risk*2,tp2:entry-risk*3,rr:2,risk,confidence:'VERY HIGH',session:'LONDON/NY OPEN'}}}
return{signal:'WAIT',reason:'NO A+ SETUP — FILTERS REJECTED WEAK TRADE',bias:b,price,rr:2,confidence:'VERY HIGH FILTER'}}