function swings(c,n=3){const hi=[],lo=[];for(let i=n;i<c.length-n;i++){let H=1,L=1;for(let j=1;j<=n;j++){if(c[i].h<=c[i-j].h||c[i].h<=c[i+j].h)H=0;if(c[i].l>=c[i-j].l||c[i].l>=c[i+j].l)L=0}if(H)hi.push(i);if(L)lo.push(i)}return{hi,lo}}
function ema(c,p){const k=2/(p+1);let v=c[0].c;for(const x of c)v=x.c*k+v*(1-k);return v}
function atr(c,p=14){let a=[];for(let i=1;i<c.length;i++)a.push(Math.max(c[i].h-c[i].l,Math.abs(c[i].h-c[i-1].c),Math.abs(c[i].l-c[i-1].c)));if(a.length<p)return 0;return a.slice(-p).reduce((x,y)=>x+y,0)/p}
function session(t){const h=new Date(t).getUTCHours();return h>=7&&h<=16}
function bias(d){const x=d.slice(-60),e20=ema(x.slice(-30),20),e50=ema(x,50),last=x.at(-1).c;return e20>e50&&last>e20?'BULLISH':e20<e50&&last<e20?'BEARISH':'NEUTRAL'}
function body(x){return Math.abs(x.c-x.o)/(x.h-x.l||1)}
export function evaluateCoreA({m5,d1,now=Date.now()}){const c=m5.filter(x=>x.t+300000<=now);if(c.length<120)return{signal:'WAIT',reason:'WAITING FOR MARKET DATA'};const price=c.at(-1).c,b=bias(d1.filter(x=>x.t+86400000<=now));const A=atr(c),{hi,lo}=swings(c,3),last=c.length-1;if(!session(c[last].t))return{signal:'WAIT',reason:'OFF SESSION — LONDON/NY ONLY',bias:b,price,rr:2};
for(let s=last-3;s>=Math.max(20,last-48);s--){const ph=hi.filter(i=>i<s).at(-1),pl=lo.filter(i=>i<s).at(-1);if(ph==null||pl==null)continue;const x=c[s],sweep=Math.max(x.h-x.c,x.c-x.l),validSweep=sweep>=A*.35;
if(b==='BULLISH'&&validSweep&&x.l<c[pl].l&&x.c>c[pl].l){let m=-1;for(let i=s+1;i<Math.min(last,s+13);i++)if(c[i].c>c[ph].h&&body(c[i])>=.55&&c[i].c-c[ph].h>=A*.2){m=i;break}if(m<0)continue;const impulse=c.slice(s,m+1),entry=impulse.reduce((z,v)=>Math.min(z,v.l),Infinity)+(c[m].h-impulse.reduce((z,v)=>Math.min(z,v.l),Infinity))*.5,sl=x.l-A*.15,risk=entry-sl;if(risk<A*.35||risk>A*3)continue;const tp1=entry+risk*2,tp2=entry+risk*3;if(c.slice(m+1,last+1).some(z=>z.l<=entry&&z.h>=entry)&&last-m<=24)return{signal:'BUY',reason:'HTF BULLISH + LIQUIDITY SWEEP + STRONG MSS + 50% RETRACEMENT',bias:b,price,entry,sl,tp1,tp2,rr:2,risk,confidence:'HIGH',session:'LONDON/NY ONLY'}}
if(b==='BEARISH'&&validSweep&&x.h>c[ph].h&&x.c<c[ph].h){let m=-1;for(let i=s+1;i<Math.min(last,s+13);i++)if(c[i].c<c[pl].l&&body(c[i])>=.55&&c[pl].l-c[i].c>=A*.2){m=i;break}if(m<0)continue;const impulse=c.slice(s,m+1),top=impulse.reduce((z,v)=>Math.max(z,v.h),-Infinity),entry=top-(top-c[m].l)*.5,sl=x.h+A*.15,risk=sl-entry;if(risk<A*.35||risk>A*3)continue;const tp1=entry-risk*2,tp2=entry-risk*3;if(c.slice(m+1,last+1).some(z=>z.l<=entry&&z.h>=entry)&&last-m<=24)return{signal:'SELL',reason:'HTF BEARISH + LIQUIDITY SWEEP + STRONG MSS + 50% RETRACEMENT',bias:b,price,entry,sl,tp1,tp2,rr:2,risk,confidence:'HIGH',session:'LONDON/NY ONLY'}}}
return{signal:'WAIT',reason:'NO HIGH-CONFIDENCE SETUP',bias:b,price,rr:2,confidence:'HIGH FILTER'}}