const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function one(host,symbol,tf,range){const u=`https://${host}/v8/finance/chart/${encodeURIComponent(symbol)}?interval=${tf}&range=${range}&includePrePost=false`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json'},cache:'no-store'});if(!r.ok)throw Error(`${host} ${symbol} ${r.status}`);const j=await r.json(),q=j?.chart?.result?.[0],v=q?.indicators?.quote?.[0];const c=(q?.timestamp||[]).map((t,i)=>({t:t*1000,o:v?.open?.[i],h:v?.high?.[i],l:v?.low?.[i],c:v?.close?.[i]})).filter(x=>[x.o,x.h,x.l,x.c].every(Number.isFinite));if(c.length<20)throw Error('insufficient candles');return c}
async function get(tf,range){for(const symbol of ['XAUUSD=X','GC=F'])for(const host of ['query1.finance.yahoo.com','query2.finance.yahoo.com']){try{return await one(host,symbol,tf,range)}catch(e){await sleep(80)}}throw Error('Market history unavailable')}
function swings(c,n=3){const hi=[],lo=[];for(let i=n;i<c.length-n;i++){let H=1,L=1;for(let j=1;j<=n;j++){if(c[i].h<=c[i-j].h||c[i].h<=c[i+j].h)H=0;if(c[i].l>=c[i-j].l||c[i].l>=c[i+j].l)L=0}if(H)hi.push(i);if(L)lo.push(i)}return{hi,lo}}
function ema(c,p){const k=2/(p+1);let v=c[0].c;for(const x of c)v=x.c*k+v*(1-k);return v}
function atr(c,p=14){const a=[];for(let i=1;i<c.length;i++)a.push(Math.max(c[i].h-c[i].l,Math.abs(c[i].h-c[i-1].c),Math.abs(c[i].l-c[i-1].c)));return a.length<p?0:a.slice(-p).reduce((x,y)=>x+y,0)/p}
function trend(c){if(c.length<60)return'NEUTRAL';const x=c.slice(-60),e20=ema(x.slice(-30),20),e50=ema(x,50),p=x.at(-1).c;return e20>e50&&p>e20?'BULLISH':e20<e50&&p<e20?'BEARISH':'NEUTRAL'}
function session(t){const h=new Date(t).getUTCHours();return h>=7&&h<=16}function body(x){return Math.abs(x.c-x.o)/(x.h-x.l||1)}
function bias(d,h,t){const db=trend(d.filter(x=>x.t+86400000<=t)),hb=trend(h.filter(x=>x.t+3600000<=t));if(db===hb&&db!=='NEUTRAL')return db;return hb!=='NEUTRAL'?hb:db}
function setup(c,d,h,last){if(last<100||!session(c[last].t))return null;const b=bias(d,h,c[last].t);if(b==='NEUTRAL')return null;const A=atr(c.slice(0,last+1)),{hi,lo}=swings(c.slice(0,last+1),3);for(let s=last-5;s>=Math.max(20,last-60);s--){const ph=hi.filter(i=>i<s).at(-1),pl=lo.filter(i=>i<s).at(-1);if(ph==null||pl==null)continue;const x=c[s],range=x.h-x.l;if(b==='BULLISH'&&x.l<c[pl].l&&x.c>c[pl].l&&body(x)>=.30&&x.c>x.l+range*.45){let m=-1;for(let i=s+1;i<Math.min(last,s+14);i++)if(c[i].c>c[ph].h&&body(c[i])>=.45){m=i;break}if(m<0)continue;const low=Math.min(...c.slice(s,m+1).map(z=>z.l)),entry=low+(c[m].h-low)*.5,sl=low-A*.1,risk=entry-sl;if(risk<A*.25||risk>A*2.5||last-m>30)continue;if(c.slice(m+1,last+1).some(z=>z.l<=entry&&z.h>=entry))return{signal:'BUY',entry,sl,tp1:entry+risk*2,tp2:entry+risk*3,risk,rr:2}}
if(b==='BEARISH'&&x.h>c[ph].h&&x.c<c[ph].h&&body(x)>=.30&&x.c<x.h-range*.45){let m=-1;for(let i=s+1;i<Math.min(last,s+14);i++)if(c[i].c<c[pl].l&&body(c[i])>=.45){m=i;break}if(m<0)continue;const top=Math.max(...c.slice(s,m+1).map(z=>z.h)),entry=top-(top-c[m].l)*.5,sl=top+A*.1,risk=sl-entry;if(risk<A*.25||risk>A*2.5||last-m>30)continue;if(c.slice(m+1,last+1).some(z=>z.l<=entry&&z.h>=entry))return{signal:'SELL',entry,sl,tp1:entry-risk*2,tp2:entry-risk*3,risk,rr:2}}}return null}
function outcome(c,i,t){for(let j=i+1;j<c.length;j++){const x=c[j];if(t.signal==='BUY'){if(x.l<=t.sl)return{result:'LOSS',points:-t.risk};if(x.h>=t.tp1)return{result:'WIN',points:t.tp1-t.entry}}else{if(x.h>=t.sl)return{result:'LOSS',points:-t.risk};if(x.l<=t.tp1)return{result:'WIN',points:t.entry-t.tp1}}}return{result:'OPEN',points:0}}
function scan(c,d,h){const out=[];let cool=-1;for(let i=100;i<c.length-1;i++){if(i<=cool)continue;const t=setup(c,d,h,i);if(!t)continue;const o=outcome(c,i,t);out.push({ts:c[i].t,...t,...o});cool=i+24}return out}
export default async function handler(req,res){try{const [c,d,h]=await Promise.all([get('5m','10d'),get('1d','1y'),get('1h','1mo')]);const all=scan(c,d,h),closed=all.filter(x=>x.result!=='OPEN'),wins=closed.filter(x=>x.result==='WIN'),losses=closed.filter(x=>x.result==='LOSS'),net=closed.reduce((s,x)=>s+x.points,0),gw=wins.reduce((s,x)=>s+x.points,0),gl=Math.abs(losses.reduce((s,x)=>s+x.points,0)),trades=all.slice(-10).reverse();res.setHeader('Cache-Control','no-store');res.status(200).json({trades,stats:{period:'Last 10 days — balanced quality filters',formed:all.length,closed:closed.length,wins:wins.length,losses:losses.length,open:all.length-closed.length,winRate:closed.length?+(wins.length/closed.length*100).toFixed(1):0,grossWin:+gw.toFixed(2),grossLoss:+gl.toFixed(2),netPoints:+net.toFixed(2),avgWin:wins.length?+(gw/wins.length).toFixed(2):0,avgLoss:losses.length?+(gl/losses.length).toFixed(2):0,profitFactor:gl?+(gw/gl).toFixed(2):0},updatedAt:Date.now()})}catch(e){res.status(503).json({error:'HISTORY_UNAVAILABLE',detail:e.message,trades:[]})}}