const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function getOne(host,symbol,tf,range){const u=`https://${host}/v8/finance/chart/${encodeURIComponent(symbol)}?interval=${tf}&range=${range}&includePrePost=false`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json'},cache:'no-store'});if(!r.ok)throw Error(`${host} ${symbol} HTTP ${r.status}`);const j=await r.json(),q=j?.chart?.result?.[0],v=q?.indicators?.quote?.[0];return(q?.timestamp||[]).map((t,i)=>({t:t*1000,o:v?.open?.[i],h:v?.high?.[i],l:v?.low?.[i],c:v?.close?.[i]})).filter(x=>[x.o,x.h,x.l,x.c].every(Number.isFinite))}
async function get(tf,range){for(const s of ['XAUUSD=X','GC=F'])for(const h of ['query1.finance.yahoo.com','query2.finance.yahoo.com']){try{const c=await getOne(h,s,tf,range);if(c.length>60)return c}catch(e){await sleep(80)}}throw Error('Market history unavailable')}
function swings(c,n=3){const hi=[],lo=[];for(let i=n;i<c.length-n;i++){let H=1,L=1;for(let j=1;j<=n;j++){if(c[i].h<=c[i-j].h||c[i].h<=c[i+j].h)H=0;if(c[i].l>=c[i-j].l||c[i].l>=c[i+j].l)L=0}if(H)hi.push(i);if(L)lo.push(i)}return{hi,lo}}
function ema(c,p){const k=2/(p+1);let v=c[0].c;for(const x of c)v=x.c*k+v*(1-k);return v}
function atr(c,p=14){if(c.length<=p)return 0;let a=[];for(let i=1;i<c.length;i++)a.push(Math.max(c[i].h-c[i].l,Math.abs(c[i].h-c[i-1].c),Math.abs(c[i].l-c[i-1].c)));return a.slice(-p).reduce((x,y)=>x+y,0)/p}
function body(x){return Math.abs(x.c-x.o)/(x.h-x.l||1)}
function session(t){const h=new Date(t).getUTCHours();return h>=7&&h<=16}
function biasAt(d,t){const x=d.filter(z=>z.t+86400000<=t).slice(-60);if(x.length<50)return'NEUTRAL';const e20=ema(x.slice(-30),20),e50=ema(x,50),last=x.at(-1).c;return e20>e50&&last>e20?'BULLISH':e20<e50&&last<e20?'BEARISH':'NEUTRAL'}
function finish(c,e,side,sl,tp){for(let i=e+1;i<c.length;i++){const x=c[i];if(side==='BUY'){if(x.l<=sl)return{result:'LOSS',exit:x.t};if(x.h>=tp)return{result:'WIN',exit:x.t}}else{if(x.h>=sl)return{result:'LOSS',exit:x.t};if(x.l<=tp)return{result:'WIN',exit:x.t}}}return{result:'OPEN',exit:null}}
function scan(c,d){const {hi,lo}=swings(c,3),out=[];let lock=-1;for(let s=25;s<c.length-26;s++){if(s<=lock||!session(c[s].t))continue;const b=biasAt(d,c[s].t);if(b==='NEUTRAL')continue;const ph=hi.filter(i=>i<s).at(-1),pl=lo.filter(i=>i<s).at(-1);if(ph==null||pl==null)continue;const x=c[s],A=atr(c.slice(Math.max(0,s-30),s+1));if(!A)continue;const sweep=Math.max(x.h-x.c,x.c-x.l);if(sweep<A*.35)continue;
if(b==='BULLISH'&&x.l<c[pl].l&&x.c>c[pl].l){let m=-1;for(let i=s+1;i<Math.min(c.length-1,s+13);i++)if(c[i].c>c[ph].h&&body(c[i])>=.55&&c[i].c-c[ph].h>=A*.2){m=i;break}if(m<0)continue;const impulse=c.slice(s,m+1),low=impulse.reduce((z,v)=>Math.min(z,v.l),Infinity),entry=low+(c[m].h-low)*.5,sl=x.l-A*.15,risk=entry-sl;if(risk<A*.35||risk>A*3)continue;let e=-1;for(let i=m+1;i<c.length-1&&i<=m+24;i++)if(c[i].l<=entry&&c[i].h>=entry){e=i;break}if(e<0)continue;const f=finish(c,e,'BUY',sl,entry+risk*2);out.push({ts:c[e].t,signal:'BUY',entry,sl,tp1:entry+risk*2,tp2:entry+risk*3,rr:2,risk,result:f.result,exit:f.exit,bias:b,confidence:'HIGH'});lock=e;continue}
if(b==='BEARISH'&&x.h>c[ph].h&&x.c<c[ph].h){let m=-1;for(let i=s+1;i<Math.min(c.length-1,s+13);i++)if(c[i].c<c[pl].l&&body(c[i])>=.55&&c[pl].l-c[i].c>=A*.2){m=i;break}if(m<0)continue;const impulse=c.slice(s,m+1),top=impulse.reduce((z,v)=>Math.max(z,v.h),-Infinity),entry=top-(top-c[m].l)*.5,sl=x.h+A*.15,risk=sl-entry;if(risk<A*.35||risk>A*3)continue;let e=-1;for(let i=m+1;i<c.length-1&&i<=m+24;i++)if(c[i].l<=entry&&c[i].h>=entry){e=i;break}if(e<0)continue;const f=finish(c,e,'SELL',sl,entry-risk*2);out.push({ts:c[e].t,signal:'SELL',entry,sl,tp1:entry-risk*2,tp2:entry-risk*3,rr:2,risk,result:f.result,exit:f.exit,bias:b,confidence:'HIGH'});lock=e}}
return out.slice(-10).reverse()}
export default async function handler(req,res){try{const [candles,daily]=await Promise.all([get('5m','5d'),get('1d','1y')]),trades=scan(candles,daily),closed=trades.filter(x=>x.result!=='OPEN'),wins=closed.filter(x=>x.result==='WIN').length,winRate=closed.length?+(wins/closed.length*100).toFixed(1):0;res.setHeader('Cache-Control','no-store, max-age=0');res.status(200).json({trades,wins,losses:closed.length-wins,closedTrades:closed.length,winRate,updatedAt:Date.now(),strategy:'HIGH-CONFIDENCE V2'})}catch(e){res.status(503).json({error:'HISTORY_UNAVAILABLE',detail:e.message,trades:[]})}}